//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchKeySettings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SearchKeySettings.LocalizedResources", typeof(LocalizedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        /// </summary>
        public static string AboutDevoted {
            get {
                return ResourceManager.GetString("AboutDevoted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application is provided &quot;AS IS&quot; without any warranties. Author isn&apos;t responsible for any damage caused by application usage.
        /// </summary>
        public static string AboutNotice {
            get {
                return ResourceManager.GetString("AboutNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, note:.
        /// </summary>
        public static string AboutPleaseNote {
            get {
                return ResourceManager.GetString("AboutPleaseNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search key settings.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bing.
        /// </summary>
        public static string Bing {
            get {
                return ResourceManager.GetString("Bing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch bing.
        /// </summary>
        public static string BingText {
            get {
                return ResourceManager.GetString("BingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string CustomUrl {
            get {
                return ResourceManager.GetString("CustomUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate to URL.
        /// </summary>
        public static string CustomUrlText {
            get {
                return ResourceManager.GetString("CustomUrlText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by application title or its author:.
        /// </summary>
        public static string EnterToSearch {
            get {
                return ResourceManager.GetString("EnterToSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid URL.
        /// </summary>
        public static string IncorrectInput {
            get {
                return ResourceManager.GetString("IncorrectInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading application list....
        /// </summary>
        public static string LoadingList {
            get {
                return ResourceManager.GetString("LoadingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No action.
        /// </summary>
        public static string NoAction {
            get {
                return ResourceManager.GetString("NoAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t do anything.
        /// </summary>
        public static string NoActionText {
            get {
                return ResourceManager.GetString("NoActionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application doesn&apos;t have a root access to your device. Please, make this application trusted using Root Manager..
        /// </summary>
        public static string NoRootAccess {
            get {
                return ResourceManager.GetString("NoRootAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter suspend mode.
        /// </summary>
        public static string PowerKey {
            get {
                return ResourceManager.GetString("PowerKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulate power key press.
        /// </summary>
        public static string PowerKeyText {
            get {
                return ResourceManager.GetString("PowerKeyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate to search page.
        /// </summary>
        public static string SearchText {
            get {
                return ResourceManager.GetString("SearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default action.
        /// </summary>
        public static string StockAction {
            get {
                return ResourceManager.GetString("StockAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set by default.
        /// </summary>
        public static string StockActionText {
            get {
                return ResourceManager.GetString("StockActionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEARCH KEY.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
